version: "3.8"

services:
  postgres:
    image: postgres:16
    networks:
      - banking-app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4:8.0
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:5050"
    networks:
      - banking-app-network
    depends_on:
      - postgres
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
        - "3004:3004"
    networks:
      - banking-app-network
    volumes:
        - ./backend/src:/code/backend/src
    depends_on:
      - postgres
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - banking-app-network
    volumes:
      - ./frontend/src:/code/frontend/src
    depends_on:
      - backend
    env_file:
      - .env

networks:
  banking-app-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
